# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65db60b3a419e3d26490bfbdec5a014be876c55811de2dd689067a63285f7ca933eb3e562bfbbde7b928498bac7416b9f34d3fc7083f9c4686255870a11f1f8d

test:
  secret_key_base: c6e51d3774310b851604cb74f2410b98c960eafec5a7786d8b00e2c02e73f3f451413e352f1fd99370f14a6fd0924ddae7c2192c523ab8deb1501443be7a806b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
